// <auto-generated />
using System;
using APTMentsAPI.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APTmentsAPI.Migrations
{
    [DbContext(typeof(AptContext))]
    partial class AptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("latin1_swedish_ci")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "latin1");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("APTMentsAPI.DBModels.Apartmentname", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Pid"));

                    b.Property<string>("Aptname")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("APTName")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Aptname"), "utf8mb4");

                    b.HasKey("Pid")
                        .HasName("PRIMARY");

                    b.ToTable("apartmentname", (string)null);
                });

            modelBuilder.Entity("APTMentsAPI.DBModels.IoParkingrow", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Pid"));

                    b.Property<string>("BlackListReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BLACK_LIST_REASON")
                        .HasComment("블랙리스트 사유");

                    b.Property<string>("CarNum")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CAR_NUM")
                        .HasComment("차량 번호");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()")
                        .HasComment("시스템 생성 일자");

                    b.Property<string>("Dong")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DONG")
                        .HasComment("동");

                    b.Property<string>("Etc")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ETC")
                        .HasComment("예약 차량의 경우");

                    b.Property<string>("Ho")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("HO")
                        .HasComment("호");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IMG_PATH")
                        .HasComment("이미지 경로");

                    b.Property<DateTime>("IoDtm")
                        .HasColumnType("datetime")
                        .HasColumnName("IO_DTM")
                        .HasComment("입-출차 일시");

                    b.Property<string>("IoGateId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_GATE_ID")
                        .HasComment("입-출차 GATE ID");

                    b.Property<string>("IoGateNm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_GATE_NM")
                        .HasComment("입-출차 GATE NM");

                    b.Property<int>("IoGubun")
                        .HasColumnType("int(11)")
                        .HasColumnName("IO_GUBUN")
                        .HasComment("입출차 구분");

                    b.Property<int>("IoLineNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("IO_LINE_NUM")
                        .HasComment("입-출차 라인번호");

                    b.Property<string>("IoLprStatus")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_LPR_STATUS")
                        .HasComment("입-출차 LPR 상태 ID");

                    b.Property<string>("IoLprStatusNm")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_LPR_STATUS_NM")
                        .HasComment("입-출차 LPR 상태 명칭");

                    b.Property<string>("IoSeq")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_SEQ")
                        .HasComment("입출차 일련번호");

                    b.Property<string>("IoStatusTp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_STATUS_TP")
                        .HasComment("입출 상태");

                    b.Property<string>("IoStatusTpNm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_STATUS_TP_NM")
                        .HasComment("입출 상태 명");

                    b.Property<string>("IoTicketTp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_TICKET_TP")
                        .HasComment("입-출차 차량 구분 ID");

                    b.Property<string>("IoTicketTpNm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_TICKET_TP_NM")
                        .HasComment("입-출차 차량 구분");

                    b.Property<string>("IsBlackList")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IS_BLACK_LIST")
                        .HasComment("블랙리스트 여부");

                    b.Property<string>("IsReservation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IS_RESERVATION")
                        .HasComment("예약차량여부");

                    b.Property<string>("IsWait")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IS_WAIT")
                        .HasComment("(입차전용) 해당차량을 입차처리할건지 대기할건지");

                    b.Property<string>("IsWaitReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IS_WAIT_REASON")
                        .HasComment("(입차전용) 대기 걸린 차량의 이유");

                    b.Property<string>("Memo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MEMO");

                    b.Property<int?>("ParkDuration")
                        .HasColumnType("int(11)")
                        .HasColumnName("PARK_DURATION")
                        .HasComment("주차시간");

                    b.Property<string>("ParkId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PARK_ID")
                        .HasComment("주차장 ID");

                    b.Property<string>("RegDtm")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("REG_DTM")
                        .HasComment("블랙리스트 등록 일시");

                    b.Property<int?>("VisitTime")
                        .HasColumnType("int(11)")
                        .HasColumnName("VISIT_TIME")
                        .HasComment("방문 시간 (방문포인트 사용 시간)");

                    b.HasKey("Pid")
                        .HasName("PRIMARY");

                    b.ToTable("io_parkingrows", null, t =>
                        {
                            t.HasComment("더함비즈 API_입출차 기록 테이블");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("APTMentsAPI.DBModels.IoParkingviewtb", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Pid"));

                    b.Property<string>("BlackListReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BLACK_LIST_REASON")
                        .HasComment("블랙리스트 사유");

                    b.Property<string>("CarNum")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CAR_NUM")
                        .HasComment("차량번호");

                    b.Property<string>("Dong")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DONG")
                        .HasComment("동");

                    b.Property<string>("Ho")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("HO")
                        .HasComment("호");

                    b.Property<DateTime?>("InDtm")
                        .HasColumnType("datetime")
                        .HasColumnName("IN_DTM")
                        .HasComment("최종입차_DT");

                    b.Property<int?>("InPid")
                        .HasColumnType("int(11)")
                        .HasColumnName("IN_PID")
                        .HasComment("최종입차_PID");

                    b.Property<string>("InStatusTp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IN_STATUS_TP")
                        .HasComment("입출 상태");

                    b.Property<string>("InStatusTpNm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IN_STATUS_TP_NM")
                        .HasComment("입출 상태 명");

                    b.Property<string>("IoSeq")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_SEQ")
                        .HasComment("입출차 일련번호");

                    b.Property<string>("IoTicketTp")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_TICKET_TP")
                        .HasComment("입-출차 차량 구분 ID");

                    b.Property<string>("IoTicketTpNm")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IO_TICKET_TP_NM")
                        .HasComment("입-출차 차량 구분 명");

                    b.Property<string>("IsBlackList")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IS_BLACK_LIST")
                        .HasComment("블랙리스트 여부");

                    b.Property<string>("Memo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MEMO");

                    b.Property<DateTime?>("OutDtm")
                        .HasColumnType("datetime")
                        .HasColumnName("OUT_DTM")
                        .HasComment("최종출차_DT");

                    b.Property<int?>("OutPid")
                        .HasColumnType("int(11)")
                        .HasColumnName("OUT_PID")
                        .HasComment("최종출차_PID");

                    b.Property<int?>("ParingDuration")
                        .HasColumnType("int(11)")
                        .HasColumnName("PARING_DURATION")
                        .HasComment("주차시간");

                    b.Property<DateTime>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()")
                        .HasComment("ROW Update 시간");

                    b.HasKey("Pid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "InPid" }, "IN_PID_202503141525");

                    b.HasIndex(new[] { "OutPid" }, "OUT_PID_202503141526");

                    b.HasIndex(new[] { "IoSeq" }, "UK_SEQ")
                        .IsUnique();

                    b.ToTable("io_parkingviewtb", null, t =>
                        {
                            t.HasComment("더함비즈 API_입출차 테이블");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("APTMentsAPI.DBModels.Patrolpadlogtb", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Pid"));

                    b.Property<string>("CarNum")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CAR_NUM")
                        .HasComment("차량번호");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()")
                        .HasComment("시스템 생성시간");

                    b.Property<string>("ParkId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PARK_ID")
                        .HasComment("주차장 ID");

                    b.Property<int>("PatrolCode")
                        .HasColumnType("int(11)")
                        .HasColumnName("PATROL_CODE")
                        .HasComment("순찰 상태 코드 1: 위반(블랙리스트), 2: 정상(입주민), 3: 방문객(현장), 4:방문객(예약)");

                    b.Property<DateTime>("PatrolDtm")
                        .HasColumnType("datetime")
                        .HasColumnName("PATROL_DTM")
                        .HasComment("순찰일시");

                    b.Property<DateTime>("PatrolEndDtm")
                        .HasColumnType("datetime")
                        .HasColumnName("PATROL_END_DTM")
                        .HasComment("순찰 종료 일시 (사용안함)");

                    b.Property<string>("PatrolImg")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PATROL_IMG")
                        .HasComment("순찰 이미지");

                    b.Property<string>("PatrolName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PATROL_NAME")
                        .HasComment("순찰상태명");

                    b.Property<string>("PatrolRemark")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PATROl_REMARK")
                        .HasComment("순찰비고");

                    b.Property<DateTime>("PatrolStartDtm")
                        .HasColumnType("datetime")
                        .HasColumnName("PATROL_START_DTM")
                        .HasComment("순찰 시작 일시 (사용안함)");

                    b.Property<int>("PatrolUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("PATROL_USER_ID")
                        .HasComment("순찰 담당자 ID (사용안함)");

                    b.Property<string>("PatrolUserNm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PATROL_USER_NM")
                        .HasComment("순찰 담당자 이름");

                    b.Property<int>("TotCnt")
                        .HasColumnType("int(11)")
                        .HasColumnName("TOT_CNT")
                        .HasComment("전체 데이터 개수 (사용안함)");

                    b.HasKey("Pid")
                        .HasName("PRIMARY");

                    b.ToTable("patrolpadlogtb", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("APTMentsAPI.DBModels.IoParkingviewtb", b =>
                {
                    b.HasOne("APTMentsAPI.DBModels.IoParkingrow", "InP")
                        .WithMany("IoParkingviewtbInPs")
                        .HasForeignKey("InPid")
                        .HasConstraintName("IN_PID_202503141525");

                    b.HasOne("APTMentsAPI.DBModels.IoParkingrow", "OutP")
                        .WithMany("IoParkingviewtbOutPs")
                        .HasForeignKey("OutPid")
                        .HasConstraintName("OUT_PID_202503141526");

                    b.Navigation("InP");

                    b.Navigation("OutP");
                });

            modelBuilder.Entity("APTMentsAPI.DBModels.IoParkingrow", b =>
                {
                    b.Navigation("IoParkingviewtbInPs");

                    b.Navigation("IoParkingviewtbOutPs");
                });
#pragma warning restore 612, 618
        }
    }
}
